2025-06-21 15:39:04.557 | ERROR    | __main__:<module>:15 - Unknow error
Traceback (most recent call last):

> File "C:\Users\Lenovo\OneDrive\Документы\GitHub\Test\Опять 25.py", line 9, in <module>
    answer_A = int(input("Input A> "))

ValueError: invalid literal for int() with base 10: 'a'
